package blogger.jscott2k.tetris.enums
enum class TileStatus{
    OUTSIDE_COLUMN_LEFT,
    OUTSIDE_COLUMN_RIGHT,
    OUTSIDE_ROW_TOP,
    OUTSIDE_ROW_BOTTOM,
    SUCCESS,
    COLLISION_WITH_TILE,
    GROUNDED_WITH_FORM_PRESERVED,
    GROUNDED_WITH_FORM_NOT_PRESERVED,
    WAITING,
    FAILED_WRONG_PRESERVATION,
    FAILED_NULL_TILE,
    LOCKED,
}